<a href="https://colab.research.google.com/github/vajihe-ameri/predict-software-bugs-in-java-classes/blob/main/commerceBreadleaf-matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Install requirements

In [1]:
!pip install sklearn pandas
!pip install prettytable

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=474d5bf3e69d4f08de751ba0e5553fff5892a98509694117660c2ead21f69ada
  Stored in directory: /root/.cache/pip/wheels/42/56/cc/4a8bf86613aafd5b7f1b310477667c1fca5c51c3ae4124a003
Successfully built sklearn
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Read dataset

In [2]:
import pandas as pd
from google.colab import drive 
drive = drive.mount('/content/drive') 

Mounted at /content/drive


Call algorithms from sklearn

In [15]:
from prettytable import PrettyTable
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.tree import export_graphviz
from IPython import display
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

'''Read data from CSV with Pandas'''
ignored_cols = ['Hash', 'LongName']

file = "drive/MyDrive/class.csv"
cols = list(pd.read_csv(file, nrows =1).dropna(axis='columns', how='all'))
cols.remove('Hash')
cols.remove('LongName')

df = pd.read_csv(file, usecols = cols)
df = df.T.drop_duplicates().T
normalized_df=(df-df.mean())/df.std()

'''Split into train and test with numpy (0.75 train, 0.25 test)'''
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.25)
actual_classes = test.iloc[:,-1:]

'''First 4 colums are the data to train'''
features = df.columns[:-1]

'''Species names to factor'''
y, bugs = pd.factorize(train['Number of Bugs'])

# random forest
'''Create random forest classifier'''
model = RandomForestClassifier(n_jobs=2, max_depth = 10, random_state = 40)
  
'''Train and test'''
model.fit(train[features], y)
preds = bugs.values[model.predict(test[features])]
actual_classes = test.iloc[:,-1:]

cr = confusion_matrix(actual_classes, preds)
tn = cr[1,0]
fn = cr[1,1]
bugs_number = tn + fn

from sklearn.metrics import f1_score
f1_weighted = f1_score(actual_classes, preds, average = 'weighted')
f1_macro = f1_score(actual_classes, preds, average = 'macro')
f1_micro = f1_score(actual_classes, preds, average = 'micro')
f1_score_weighted = "%.2f"%round(f1_weighted, 2)
f1_score_macro = "%.2f"%round(f1_macro, 2)
f1_score_micro = "%.2f"%round(f1_micro, 2)
  
print('Random forest')
head = PrettyTable(['confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row([cr, f1_score_weighted, f1_score_macro, f1_score_micro, bugs_number]) 
print(head)

# logistic regression
'''Create logistic regression classifier'''  
model1 = LogisticRegression()
model2 = LogisticRegression(solver='sag', penalty='l2',n_jobs=-1, random_state=10)
model3 = LogisticRegression(solver='saga', penalty='l2',n_jobs=-1, random_state=20)
model4 = LogisticRegression(solver='liblinear', penalty='l1',n_jobs=-1, random_state=0)
model5 = LogisticRegression(solver='liblinear', penalty='l2',n_jobs=-1, random_state=90)
model6 = LogisticRegression(solver='lbfgs', penalty='l2',n_jobs=-1, random_state=50)
model7 = LogisticRegression(solver='newton-cg', penalty='l2',n_jobs=-1, random_state=90)

'''Train and test'''
model1.fit(train[features], y)
model2.fit(train[features], y)
model3.fit(train[features], y)
model4.fit(train[features], y)
model5.fit(train[features], y)
model6.fit(train[features], y)
model7.fit(train[features], y)

preds1 = bugs.values[model1.predict(test[features])]
preds2 = bugs.values[model2.predict(test[features])]
preds3 = bugs.values[model3.predict(test[features])]
preds4 = bugs.values[model4.predict(test[features])]
preds5 = bugs.values[model5.predict(test[features])]
preds6 = bugs.values[model6.predict(test[features])]
preds7 = bugs.values[model7.predict(test[features])]

cr1 = confusion_matrix(actual_classes, preds1)
cr2 = confusion_matrix(actual_classes, preds2)
cr3 = confusion_matrix(actual_classes, preds3)
cr4 = confusion_matrix(actual_classes, preds4)
cr5 = confusion_matrix(actual_classes, preds5)
cr6 = confusion_matrix(actual_classes, preds6)
cr7 = confusion_matrix(actual_classes, preds7)

tn1 = cr1[1,0]
fn1 = cr1[1,1]
tn2 = cr2[1,0]
fn2 = cr2[1,1]
tn3 = cr3[1,0]
fn3 = cr3[1,1]
tn4 = cr4[1,0]
fn4 = cr4[1,1]
tn5 = cr5[1,0]
fn5 = cr5[1,1]
tn6 = cr6[1,0]
fn6 = cr6[1,1]
tn7 = cr7[1,0]
fn7 = cr7[1,1]

bugs_number1 = tn1 + fn1
bugs_number2 = tn2 + fn2
bugs_number3 = tn3 + fn3
bugs_number4 = tn4 + fn4
bugs_number5 = tn5 + fn5
bugs_number6 = tn6 + fn6
bugs_number7 = tn7 + fn7

from sklearn.metrics import f1_score

f1_weighted1 = f1_score(actual_classes, preds1, average = 'weighted')
f1_weighted2 = f1_score(actual_classes, preds2, average = 'weighted')
f1_weighted3 = f1_score(actual_classes, preds3, average = 'weighted')
f1_weighted4 = f1_score(actual_classes, preds4, average = 'weighted')
f1_weighted5 = f1_score(actual_classes, preds5, average = 'weighted')
f1_weighted6 = f1_score(actual_classes, preds6, average = 'weighted')
f1_weighted7 = f1_score(actual_classes, preds7, average = 'weighted')

f1_macro1 = f1_score(actual_classes, preds1, average = 'macro')
f1_macro2 = f1_score(actual_classes, preds2, average = 'macro')
f1_macro3 = f1_score(actual_classes, preds3, average = 'macro')
f1_macro4 = f1_score(actual_classes, preds4, average = 'macro')
f1_macro5 = f1_score(actual_classes, preds5, average = 'macro')
f1_macro6 = f1_score(actual_classes, preds6, average = 'macro')
f1_macro7 = f1_score(actual_classes, preds7, average = 'macro')

f1_micro1 = f1_score(actual_classes, preds1, average = 'micro')
f1_micro2 = f1_score(actual_classes, preds2, average = 'micro')
f1_micro3 = f1_score(actual_classes, preds3, average = 'micro')
f1_micro4 = f1_score(actual_classes, preds4, average = 'micro')
f1_micro5 = f1_score(actual_classes, preds5, average = 'micro')
f1_micro6 = f1_score(actual_classes, preds6, average = 'micro')
f1_micro7 = f1_score(actual_classes, preds7, average = 'micro')

f1_score_weighted1 = "%.2f"%round(f1_weighted1, 2)
f1_score_weighted2 = "%.2f"%round(f1_weighted2, 2)
f1_score_weighted3 = "%.2f"%round(f1_weighted3, 2)
f1_score_weighted4 = "%.2f"%round(f1_weighted4, 2)
f1_score_weighted5 = "%.2f"%round(f1_weighted5, 2)
f1_score_weighted6 = "%.2f"%round(f1_weighted6, 2)
f1_score_weighted7 = "%.2f"%round(f1_weighted7, 2)

f1_score_macro1 = "%.2f"%round(f1_macro1, 2)
f1_score_macro2 = "%.2f"%round(f1_macro2, 2)
f1_score_macro3 = "%.2f"%round(f1_macro3, 2)
f1_score_macro4 = "%.2f"%round(f1_macro4, 2)
f1_score_macro5 = "%.2f"%round(f1_macro5, 2)
f1_score_macro6 = "%.2f"%round(f1_macro6, 2)
f1_score_macro7 = "%.2f"%round(f1_macro7, 2)

f1_score_micro1 = "%.2f"%round(f1_micro1, 2)
f1_score_micro2 = "%.2f"%round(f1_micro2, 2)
f1_score_micro3 = "%.2f"%round(f1_micro3, 2)
f1_score_micro4 = "%.2f"%round(f1_micro4, 2)
f1_score_micro5 = "%.2f"%round(f1_micro5, 2)
f1_score_micro6 = "%.2f"%round(f1_micro6, 2)
f1_score_micro7 = "%.2f"%round(f1_micro7, 2)

print('Logistic regression')
head = PrettyTable(['random_state', 'solver', 'penalty', 'n_jobs', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row(['', '', '', '', cr1, f1_score_weighted1, f1_score_macro1, f1_score_micro1, bugs_number1]) 
head.add_row(['10', 'sag', 'l2', '-1', cr2, f1_score_weighted2, f1_score_macro2, f1_score_micro2, bugs_number2]) 
head.add_row(['20', 'saga', 'l2', '-1', cr3, f1_score_weighted3, f1_score_macro3, f1_score_micro3, bugs_number3]) 
head.add_row(['0', 'liblinear', 'l1', '-1', cr4, f1_score_weighted4, f1_score_macro4, f1_score_micro4, bugs_number4]) 
head.add_row(['90', 'liblinear', 'l2', '-1', cr5, f1_score_weighted5, f1_score_macro5, f1_score_micro5, bugs_number5]) 
head.add_row(['50', 'lbfgs', 'l2', '-1', cr6, f1_score_weighted6, f1_score_macro6, f1_score_micro6, bugs_number6]) 
head.add_row(['90', 'newton-cg', 'l2', '-1', cr7, f1_score_weighted7, f1_score_macro7, f1_score_micro7, bugs_number7]) 
print(head)

# naive bayes
'''Create naive bayes classifier'''
model = GaussianNB()
  
'''Train and test'''
model.fit(train[features], y)
preds = bugs.values[model.predict(test[features])]
actual_classes = test.iloc[:,-1:]

cr = confusion_matrix(actual_classes, preds)
tn = cr[1,0]
fn = cr[1,1]
bugs_number = tn + fn

from sklearn.metrics import f1_score
f1_weighted = f1_score(actual_classes, preds, average = 'weighted')
f1_macro = f1_score(actual_classes, preds, average = 'macro')
f1_micro = f1_score(actual_classes, preds, average = 'micro')
f1_score_weighted = "%.2f"%round(f1_weighted, 2)
f1_score_macro = "%.2f"%round(f1_macro, 2)
f1_score_micro = "%.2f"%round(f1_micro, 2)
  
print('Naive bayes')
head = PrettyTable(['confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row([cr, f1_score_weighted, f1_score_macro, f1_score_micro, bugs_number]) 
print(head)

# Artificial Neural Network
'''Create Artificial Neural Network classifier'''
model = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
  
'''Train and test'''
model.fit(train[features], y)
preds = bugs.values[model.predict(test[features])]
actual_classes = test.iloc[:,-1:]

cr = confusion_matrix(actual_classes, preds)
tn = cr[1,0]
fn = cr[1,1]
bugs_number = tn + fn

from sklearn.metrics import f1_score
f1_weighted = f1_score(actual_classes, preds, average = 'weighted')
f1_macro = f1_score(actual_classes, preds, average = 'macro')
f1_micro = f1_score(actual_classes, preds, average = 'micro')
f1_score_weighted = "%.2f"%round(f1_weighted, 2)
f1_score_macro = "%.2f"%round(f1_macro, 2)
f1_score_micro = "%.2f"%round(f1_micro, 2)
  
print('Artificial neural network')
head = PrettyTable(['confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row([cr, f1_score_weighted, f1_score_macro, f1_score_micro, bugs_number]) 
print(head)

# Multi-Layer Perceptron Neural Network
'''Create Artificial Neural Network classifier'''
model = MLPClassifier()
  
'''Train and test'''
model.fit(train[features], y)
preds = bugs.values[model.predict(test[features])]
actual_classes = test.iloc[:,-1:]

cr = confusion_matrix(actual_classes, preds)
tn = cr[1,0]
fn = cr[1,1]
bugs_number = tn + fn

from sklearn.metrics import f1_score
f1_weighted = f1_score(actual_classes, preds, average = 'weighted')
f1_macro = f1_score(actual_classes, preds, average = 'macro')
f1_micro = f1_score(actual_classes, preds, average = 'micro')
f1_score_weighted = "%.2f"%round(f1_weighted, 2)
f1_score_macro = "%.2f"%round(f1_macro, 2)
f1_score_micro = "%.2f"%round(f1_micro, 2)
  
print('Multi layer perceptron neural network')
head = PrettyTable(['confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row([cr, f1_score_weighted, f1_score_macro, f1_score_micro, bugs_number]) 
print(head)

# Support vector machine
'''Create Artificial Neural Network classifier'''
model = SVC(C=1.0, random_state=1, kernel='linear')
  
'''Train and test'''
model.fit(train[features], y)
preds = bugs.values[model.predict(test[features])]
actual_classes = test.iloc[:,-1:]

cr = confusion_matrix(actual_classes, preds)
tn = cr[1,0]
fn = cr[1,1]
bugs_number = tn + fn

from sklearn.metrics import f1_score
f1_weighted = f1_score(actual_classes, preds, average = 'weighted')
f1_macro = f1_score(actual_classes, preds, average = 'macro')
f1_micro = f1_score(actual_classes, preds, average = 'micro')
f1_score_weighted = "%.2f"%round(f1_weighted, 2)
f1_score_macro = "%.2f"%round(f1_macro, 2)
f1_score_micro = "%.2f"%round(f1_micro, 2)
  
print('Support vector machine')
head = PrettyTable(['confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row([cr, f1_score_weighted, f1_score_macro, f1_score_micro, bugs_number]) 
print(head)

# decision tree
'''Create decision tree classifier'''    
model = tree.DecisionTreeClassifier(max_depth = 1,  random_state = 90)
  
'''Train and test'''
model.fit(train[features], y)
preds = bugs.values[model.predict(test[features])]
actual_classes = test.iloc[:,-1:]

cr = confusion_matrix(actual_classes, preds)
tn = cr[1,0]
fn = cr[1,1]
bugs_number = tn + fn

from sklearn.metrics import f1_score
f1_weighted = f1_score(actual_classes, preds, average = 'weighted')
f1_macro = f1_score(actual_classes, preds, average = 'macro')
f1_micro = f1_score(actual_classes, preds, average = 'micro')
f1_score_weighted = "%.2f"%round(f1_weighted, 2)
f1_score_macro = "%.2f"%round(f1_macro, 2)
f1_score_micro = "%.2f"%round(f1_micro, 2)
  
print('Decision tree')
head = PrettyTable(['confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro', 'bugs-number']) 
head.add_row([cr, f1_score_weighted, f1_score_macro, f1_score_micro, bugs_number]) 
print(head)


Random forest
+------------------+-------------------+----------------+----------------+-------------+
| confusion_matrix | f1_score_weighted | f1_score_macro | f1_score_micro | bugs-number |
+------------------+-------------------+----------------+----------------+-------------+
|    [[130   4]    |        0.85       |      0.56      |      0.88      |      16     |
|    [ 14   2]]    |                   |                |                |             |
+------------------+-------------------+----------------+----------------+-------------+


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1526: UserWarning: 'n_jobs' > 1 does not h

Logistic regression
+--------------+-----------+---------+--------+------------------+-------------------+----------------+----------------+-------------+
| random_state |   solver  | penalty | n_jobs | confusion_matrix | f1_score_weighted | f1_score_macro | f1_score_micro | bugs-number |
+--------------+-----------+---------+--------+------------------+-------------------+----------------+----------------+-------------+
|              |           |         |        |  [[132   2   0]  |        0.84       |      0.31      |      0.88      |      15     |
|              |           |         |        |   [ 15   0   1]  |                   |                |                |             |
|              |           |         |        |  [  0   0   0]]  |                   |                |                |             |
|      10      |    sag    |    l2   |   -1   |  [[134   0   0]  |        0.85       |      0.32      |      0.89      |      15     |
|              |           |       