<a href="https://colab.research.google.com/github/vajihe-ameri/predict-software-bugs-in-java-classes/blob/main/tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Install requirements

In [6]:
!pip install sklearn pandas
!pip install prettytable

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Read dataset

In [7]:
import pandas as pd
from google.colab import drive 
drive = drive.mount('/content/drive') 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Call algorithms from sklearntrain_featurestrain_fea

In [1]:
from prettytable import PrettyTable
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.tree import export_graphviz
from IPython import display
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:

  '''Read data from CSV with Pandas'''
  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")
  print(f'Project => {project}')
  df.info()
  print('-------------------------------------------------------------------------------')

Project => elasticsearch
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24994 entries, 0 to 24993
Data columns (total 86 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   CC                                 24994 non-null  float64
 1   CCL                                24994 non-null  float64
 2   CCO                                24994 non-null  float64
 3   CI                                 24994 non-null  float64
 4   CLC                                24994 non-null  float64
 5   CLLC                               24994 non-null  float64
 6   LDC                                24994 non-null  float64
 7   LLDC                               24994 non-null  float64
 8   LCOM5                              24994 non-null  float64
 9   NL                                 24994 non-null  float64
 10  NLE                                24994 non-null  float64
 11  WMC                          

random forest

In [8]:
print('Random forest')
projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:
  print(f'Project: {project}')

  '''Read data from CSV with Pandas'''
  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")

  '''Split into train and test with numpy (0.75 train, 0.25 test)'''
  from sklearn.model_selection import train_test_split
  train, test = train_test_split(df, test_size=0.25)

  df=(df-df.mean())/df.std()

  test_target = test.pop('Number of Bugs')
  test_features = test
 
  train_target = train.pop('Number of Bugs')
  train_features = train
  
  '''Create random forest classifier'''
  model1 = RandomForestClassifier()
  model2 = RandomForestClassifier(n_estimators=100, criterion = 'gini', max_depth = 1, random_state = 80)
  model3 = RandomForestClassifier(n_estimators=90, criterion = 'entropy' , max_depth = 10, random_state = 50)
  model4 = RandomForestClassifier(n_estimators=50, criterion = 'entropy', max_depth = 20, random_state = 60)
  model5 = RandomForestClassifier(n_estimators=1, criterion = 'gini', max_depth = 30, random_state = 40)

  '''Train and test'''
  model1.fit(train_features, train_target)
  model2.fit(train_features, train_target)
  model3.fit(train_features, train_target)
  model4.fit(train_features, train_target)
  model5.fit(train_features, train_target)

  preds1 = model1.predict(test_features)
  preds2 = model2.predict(test_features)
  preds3 = model3.predict(test_features)
  preds4 = model4.predict(test_features)
  preds5 = model5.predict(test_features)

  cr1 = confusion_matrix(test_target, preds1)
  cr2 = confusion_matrix(test_target, preds2)
  cr3 = confusion_matrix(test_target, preds3)
  cr4 = confusion_matrix(test_target, preds4)
  cr5 = confusion_matrix(test_target, preds5)

  tn, fp, fn, tp = confusion_matrix(list(test_target), list(preds1), labels=[0, 1]).ravel()
  print('bugs-number:', tn+fn)

  from sklearn.metrics import f1_score

  f1_weighted1 = f1_score(test_target, preds1, average = 'weighted')
  f1_weighted2 = f1_score(test_target, preds2, average = 'weighted')
  f1_weighted3 = f1_score(test_target, preds3, average = 'weighted')
  f1_weighted4 = f1_score(test_target, preds4, average = 'weighted')
  f1_weighted5 = f1_score(test_target, preds5, average = 'weighted')

  f1_macro1 = f1_score(test_target, preds1, average = 'macro')
  f1_macro2 = f1_score(test_target, preds2, average = 'macro')
  f1_macro3 = f1_score(test_target, preds3, average = 'macro')
  f1_macro4 = f1_score(test_target, preds4, average = 'macro')
  f1_macro5 = f1_score(test_target, preds5, average = 'macro')

  f1_micro1 = f1_score(test_target, preds1, average = 'micro')
  f1_micro2 = f1_score(test_target, preds2, average = 'micro')
  f1_micro3 = f1_score(test_target, preds3, average = 'micro')
  f1_micro4 = f1_score(test_target, preds4, average = 'micro')
  f1_micro5 = f1_score(test_target, preds5, average = 'micro')

  f1_score_weighted1 = "%.2f"%round(f1_weighted1, 2)
  f1_score_weighted2 = "%.2f"%round(f1_weighted2, 2)
  f1_score_weighted3 = "%.2f"%round(f1_weighted3, 2)
  f1_score_weighted4 = "%.2f"%round(f1_weighted4, 2)
  f1_score_weighted5 = "%.2f"%round(f1_weighted5, 2)

  f1_score_macro1 = "%.2f"%round(f1_macro1, 2)
  f1_score_macro2 = "%.2f"%round(f1_macro2, 2)
  f1_score_macro3 = "%.2f"%round(f1_macro3, 2)
  f1_score_macro4 = "%.2f"%round(f1_macro4, 2)
  f1_score_macro5 = "%.2f"%round(f1_macro5, 2)

  f1_score_micro1 = "%.2f"%round(f1_micro1, 2)
  f1_score_micro2 = "%.2f"%round(f1_micro2, 2)
  f1_score_micro3 = "%.2f"%round(f1_micro3, 2)
  f1_score_micro4 = "%.2f"%round(f1_micro4, 2)
  f1_score_micro5 = "%.2f"%round(f1_micro5, 2)

  head = PrettyTable(['random_state', 'n_estimatorsint', 'criterion', 'max_depth', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro']) 
  head.add_row(['', '', '', '', cr1, f1_score_weighted1, f1_score_macro1, f1_score_micro1]) 
  head.add_row(['80', '10', 'gini', '1', cr2, f1_score_weighted2, f1_score_macro2, f1_score_micro2]) 
  head.add_row(['50', '100', 'entropy', '10', cr3, f1_score_weighted3, f1_score_macro3, f1_score_micro3]) 
  head.add_row(['60', '50', 'entropy', '20', cr4, f1_score_weighted4, f1_score_macro4, f1_score_micro4]) 
  head.add_row(['40', '1', 'gini', '30', cr5, f1_score_weighted5, f1_score_macro5, f1_score_micro5]) 
  print(head)

Random forest
Project: elasticsearch
bugs-number: 3173
+--------------+-----------------+-----------+-----------+--------------------------------------------------+-------------------+----------------+----------------+
| random_state | n_estimatorsint | criterion | max_depth |                 confusion_matrix                 | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+-----------------+-----------+-----------+--------------------------------------------------+-------------------+----------------+----------------+
|              |                 |           |           | [[2008  923  184   17    0    5    0    0    0]  |        0.42       |      0.21      |      0.43      |
|              |                 |           |           |  [1165  457  207   47    1    2    2    0    0]  |                   |                |                |
|              |                 |           |           |  [ 289  252  159  119    8    2    1    0    0]  |                

logistic regression

In [9]:
print('Logistic regression')
projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:
  print(f'Project: {project}')

  '''Read data from CSV with Pandas'''
  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")

  '''Split into train and test with numpy (0.75 train, 0.25 test)'''
  from sklearn.model_selection import train_test_split
  train, test = train_test_split(df, test_size=0.25)

  df=(df-df.mean())/df.std()

  test_target = test.pop('Number of Bugs')
  test_features = test
 
  train_target = train.pop('Number of Bugs')
  train_features = train
  
  '''Create logistic regression classifier'''  
  model1 = LogisticRegression()
  model2 = LogisticRegression(solver='sag', penalty='l2',n_jobs=-1, random_state=10)
  model3 = LogisticRegression(solver='saga', penalty='l2',n_jobs=-1, random_state=20)
  model4 = LogisticRegression(solver='liblinear', penalty='l1',n_jobs=-1, random_state=0)
  model5 = LogisticRegression(solver='liblinear', penalty='l2',n_jobs=-1, random_state=90)
  model6 = LogisticRegression(solver='lbfgs', penalty='l2',n_jobs=-1, random_state=50)
  model7 = LogisticRegression(solver='newton-cg', penalty='l2',n_jobs=-1, random_state=90)

  '''Train and test'''
  model1.fit(train_features, train_target)
  model2.fit(train_features, train_target)
  model3.fit(train_features, train_target)
  model4.fit(train_features, train_target)
  model5.fit(train_features, train_target)
  model6.fit(train_features, train_target)
  model7.fit(train_features, train_target)

  preds1 = model1.predict(test_features)
  preds2 = model2.predict(test_features)
  preds3 = model3.predict(test_features)
  preds4 = model4.predict(test_features)
  preds5 = model5.predict(test_features)
  preds6 = model5.predict(test_features)
  preds7 = model5.predict(test_features)

  cr1 = confusion_matrix(test_target, preds1)
  cr2 = confusion_matrix(test_target, preds2)
  cr3 = confusion_matrix(test_target, preds3)
  cr4 = confusion_matrix(test_target, preds4)
  cr5 = confusion_matrix(test_target, preds5)
  cr6 = confusion_matrix(test_target, preds5)
  cr7 = confusion_matrix(test_target, preds5)

  tn, fp, fn, tp = confusion_matrix(list(test_target), list(preds1), labels=[0, 1]).ravel()
  print('bugs-number:', tn+fn)

  from sklearn.metrics import f1_score

  f1_weighted1 = f1_score(test_target, preds1, average = 'weighted')
  f1_weighted2 = f1_score(test_target, preds2, average = 'weighted')
  f1_weighted3 = f1_score(test_target, preds3, average = 'weighted')
  f1_weighted4 = f1_score(test_target, preds4, average = 'weighted')
  f1_weighted5 = f1_score(test_target, preds5, average = 'weighted')
  f1_weighted6 = f1_score(test_target, preds5, average = 'weighted')
  f1_weighted7 = f1_score(test_target, preds5, average = 'weighted')

  f1_macro1 = f1_score(test_target, preds1, average = 'macro')
  f1_macro2 = f1_score(test_target, preds2, average = 'macro')
  f1_macro3 = f1_score(test_target, preds3, average = 'macro')
  f1_macro4 = f1_score(test_target, preds4, average = 'macro')
  f1_macro5 = f1_score(test_target, preds5, average = 'macro')
  f1_macro6 = f1_score(test_target, preds5, average = 'macro')
  f1_macro7 = f1_score(test_target, preds5, average = 'macro')

  f1_micro1 = f1_score(test_target, preds1, average = 'micro')
  f1_micro2 = f1_score(test_target, preds2, average = 'micro')
  f1_micro3 = f1_score(test_target, preds3, average = 'micro')
  f1_micro4 = f1_score(test_target, preds4, average = 'micro')
  f1_micro5 = f1_score(test_target, preds5, average = 'micro')
  f1_micro6 = f1_score(test_target, preds5, average = 'micro')
  f1_micro7 = f1_score(test_target, preds5, average = 'micro')
 
  f1_score_weighted1 = "%.2f"%round(f1_weighted1, 2)
  f1_score_weighted2 = "%.2f"%round(f1_weighted2, 2)
  f1_score_weighted3 = "%.2f"%round(f1_weighted3, 2)
  f1_score_weighted4 = "%.2f"%round(f1_weighted4, 2)
  f1_score_weighted5 = "%.2f"%round(f1_weighted5, 2)
  f1_score_weighted6 = "%.2f"%round(f1_weighted6, 2)
  f1_score_weighted7 = "%.2f"%round(f1_weighted7, 2)

  f1_score_macro1 = "%.2f"%round(f1_macro1, 2)
  f1_score_macro2 = "%.2f"%round(f1_macro2, 2)
  f1_score_macro3 = "%.2f"%round(f1_macro3, 2)
  f1_score_macro4 = "%.2f"%round(f1_macro4, 2)
  f1_score_macro5 = "%.2f"%round(f1_macro5, 2)
  f1_score_macro6 = "%.2f"%round(f1_macro6, 2)
  f1_score_macro7 = "%.2f"%round(f1_macro7, 2)

  f1_score_micro1 = "%.2f"%round(f1_micro1, 2)
  f1_score_micro2 = "%.2f"%round(f1_micro2, 2)
  f1_score_micro3 = "%.2f"%round(f1_micro3, 2)
  f1_score_micro4 = "%.2f"%round(f1_micro4, 2)
  f1_score_micro5 = "%.2f"%round(f1_micro5, 2)
  f1_score_micro6 = "%.2f"%round(f1_micro6, 2)
  f1_score_micro7 = "%.2f"%round(f1_micro7, 2)

  head = PrettyTable(['random_state', 'solver', 'penalty', 'n_jobs', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro']) 
  head.add_row(['', '', '', '', cr1, f1_score_weighted1, f1_score_macro1, f1_score_micro1]) 
  head.add_row(['10', 'sag', 'l2', '-1', cr2, f1_score_weighted2, f1_score_macro2, f1_score_micro2]) 
  head.add_row(['20', 'saga', 'l2', '-1', cr3, f1_score_weighted3, f1_score_macro3, f1_score_micro3]) 
  head.add_row(['0', 'liblinear', 'l1', '-1', cr4, f1_score_weighted4, f1_score_macro4, f1_score_micro4]) 
  head.add_row(['90', 'liblinear', 'l2', '-1', cr5, f1_score_weighted5, f1_score_macro5, f1_score_micro5]) 
  head.add_row(['50', 'lbfgs', 'l2', '-1', cr6, f1_score_weighted6, f1_score_macro6, f1_score_micro6]) 
  head.add_row(['90', 'newton-cg', 'l2', '-1', cr7, f1_score_weighted7, f1_score_macro7, f1_score_micro7]) 
  print(head)

Logistic regression
Project: elasticsearch


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1526: UserWarning: 'n_jobs' > 1 does not h

bugs-number: 4471
+--------------+-----------+---------+--------+--------------------------------------------------+-------------------+----------------+----------------+
| random_state |   solver  | penalty | n_jobs |                 confusion_matrix                 | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+-----------+---------+--------+--------------------------------------------------+-------------------+----------------+----------------+
|              |           |         |        | [[2853  217   48    6    8   22    3    0    1]  |        0.37       |      0.09      |      0.48      |
|              |           |         |        |  [1618  132   35    3    7    5    0    0    0]  |                   |                |                |
|              |           |         |        |  [ 754   83   26    0    1    0    2    0    0]  |                   |                |                |
|              |           |         |        |  [ 271   34    6

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1526: UserWarning: 'n_jobs' > 1 does not h

bugs-number: 79
+--------------+-----------+---------+--------+------------------+-------------------+----------------+----------------+
| random_state |   solver  | penalty | n_jobs | confusion_matrix | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+-----------+---------+--------+------------------+-------------------+----------------+----------------+
|              |           |         |        |  [[52 11  1  3]  |        0.55       |      0.33      |      0.57      |
|              |           |         |        |   [27  8  2  1]  |                   |                |                |
|              |           |         |        |   [ 1  0  1  0]  |                   |                |                |
|              |           |         |        |  [ 0  0  0  0]]  |                   |                |                |
|      10      |    sag    |    l2   |   -1   |   [[56 11  0]    |        0.50       |      0.29      |      0.56      |
|              |

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1526: UserWarning: 'n_jobs' > 1 does not h

bugs-number: 13
+--------------+-----------+---------+--------+------------------+-------------------+----------------+----------------+
| random_state |   solver  | penalty | n_jobs | confusion_matrix | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+-----------+---------+--------+------------------+-------------------+----------------+----------------+
|              |           |         |        |      [[9 4]      |        0.53       |      0.35      |      0.53      |
|              |           |         |        |      [4 0]]      |                   |                |                |
|      10      |    sag    |    l2   |   -1   |     [[11  2]     |        0.60       |      0.39      |      0.65      |
|              |           |         |        |     [ 4  0]]     |                   |                |                |
|      20      |    saga   |    l2   |   -1   |     [[11  2]     |        0.60       |      0.39      |      0.65      |
|              |

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1526: UserWarning: 'n_jobs' > 1 does not h

bugs-number: 518
+--------------+-----------+---------+--------+-----------------------------------------------------+-------------------+----------------+----------------+
| random_state |   solver  | penalty | n_jobs |                   confusion_matrix                  | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+-----------+---------+--------+-----------------------------------------------------+-------------------+----------------+----------------+
|              |           |         |        |  [[349  13  10   1   0   2   0   2   0   0   2   0] |        0.43       |      0.10      |      0.52      |
|              |           |         |        |   [169  19  13   2   0   5   0   0   0   0   1   0] |                   |                |                |
|              |           |         |        |   [ 47   9  16   1   0   2   0   0   0   0   1   0] |                   |                |                |
|              |           |         |        |

naive bayes

In [10]:
print('Naive bayes')
projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:
  print(f'Project: {project}')

  '''Read data from CSV with Pandas'''

  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")

  '''Split into train and test with numpy (0.75 train, 0.25 test)'''
  from sklearn.model_selection import train_test_split
  train, test = train_test_split(df, test_size=0.25)

  df=(df-df.mean())/df.std()

  test_target = test.pop('Number of Bugs')
  test_features = test
 
  train_target = train.pop('Number of Bugs')
  train_features = train
  
  '''Create random forest classifier'''
  model1 = GaussianNB()
  model2 = GaussianNB(var_smoothing = 1e-11)
  model3 = GaussianNB(var_smoothing = 1e-09)
  model4 = GaussianNB(var_smoothing = 1e-10)

  '''Train and test'''
  model1.fit(train_features, train_target)
  model2.fit(train_features, train_target)
  model3.fit(train_features, train_target)
  model4.fit(train_features, train_target)

  preds1 = model1.predict(test_features)
  preds2 = model2.predict(test_features)
  preds3 = model3.predict(test_features)
  preds4 = model4.predict(test_features)

  cr1 = confusion_matrix(test_target, preds1)
  cr2 = confusion_matrix(test_target, preds2)
  cr3 = confusion_matrix(test_target, preds3)
  cr4 = confusion_matrix(test_target, preds4)

  tn, fp, fn, tp = confusion_matrix(list(test_target), list(preds1), labels=[0, 1]).ravel()
  print('bugs-number:', tn+fn)

  from sklearn.metrics import f1_score

  f1_weighted1 = f1_score(test_target, preds1, average = 'weighted')
  f1_weighted2 = f1_score(test_target, preds2, average = 'weighted')
  f1_weighted3 = f1_score(test_target, preds3, average = 'weighted')
  f1_weighted4 = f1_score(test_target, preds4, average = 'weighted')

  f1_macro1 = f1_score(test_target, preds1, average = 'macro')
  f1_macro2 = f1_score(test_target, preds2, average = 'macro')
  f1_macro3 = f1_score(test_target, preds3, average = 'macro')
  f1_macro4 = f1_score(test_target, preds4, average = 'macro')

  f1_micro1 = f1_score(test_target, preds1, average = 'micro')
  f1_micro2 = f1_score(test_target, preds2, average = 'micro')
  f1_micro3 = f1_score(test_target, preds3, average = 'micro')
  f1_micro4 = f1_score(test_target, preds4, average = 'micro')

  f1_score_weighted1 = "%.2f"%round(f1_weighted1, 2)
  f1_score_weighted2 = "%.2f"%round(f1_weighted2, 2)
  f1_score_weighted3 = "%.2f"%round(f1_weighted3, 2)
  f1_score_weighted4 = "%.2f"%round(f1_weighted4, 2)

  f1_score_macro1 = "%.2f"%round(f1_macro1, 2)
  f1_score_macro2 = "%.2f"%round(f1_macro2, 2)
  f1_score_macro3 = "%.2f"%round(f1_macro3, 2)
  f1_score_macro4 = "%.2f"%round(f1_macro4, 2)

  f1_score_micro1 = "%.2f"%round(f1_micro1, 2)
  f1_score_micro2 = "%.2f"%round(f1_micro2, 2)
  f1_score_micro3 = "%.2f"%round(f1_micro3, 2)
  f1_score_micro4 = "%.2f"%round(f1_micro4, 2)

  head = PrettyTable(['var_smoothing', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro']) 
  head.add_row(['', cr1, f1_score_weighted1, f1_score_macro1, f1_score_micro1]) 
  head.add_row(['1e-11', cr2, f1_score_weighted2, f1_score_macro2, f1_score_micro2]) 
  head.add_row(['1e-9', cr3, f1_score_weighted3, f1_score_macro3, f1_score_micro3]) 
  head.add_row(['1e-10', cr4, f1_score_weighted4, f1_score_macro4, f1_score_micro4]) 
  print(head)

Naive bayes
Project: elasticsearch
bugs-number: 3703
+---------------+--------------------------------------------------+-------------------+----------------+----------------+
| var_smoothing |                 confusion_matrix                 | f1_score_weighted | f1_score_macro | f1_score_micro |
+---------------+--------------------------------------------------+-------------------+----------------+----------------+
|               | [[2384   47  129  141   47  262  130    0    1]  |        0.35       |      0.12      |      0.41      |
|               |  [1319   34  119   92   58  184   92    1    0]  |                   |                |                |
|               |  [ 520    8   71   52   22   70   71    1    0]  |                   |                |                |
|               |  [ 162    2   21   23   18   33   21    2    0]  |                   |                |                |
|               |  [  29    1    3    7    3   13    9    0    0]  |                  

Multi-Layer Perceptron Neural Network

In [11]:
print('Multi layer perceptron neural network')
projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:
  print(f'Project: {project}')

  '''Read data from CSV with Pandas'''
  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")

  '''Split into train and test with numpy (0.75 train, 0.25 test)'''
  from sklearn.model_selection import train_test_split
  train, test = train_test_split(df, test_size=0.25)

  df=(df-df.mean())/df.std()

  test_target = test.pop('Number of Bugs')
  test_features = test
 
  train_target = train.pop('Number of Bugs')
  train_features = train
  
  '''Create Artificial Neural Network classifier'''
  model1 = MLPClassifier()
  model2 = MLPClassifier(solver='lbfgs', alpha=0.01, hidden_layer_sizes=(5, 2), activation = 'tanh', random_state=10)
  model3 = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(150, 100, 50), activation = 'logistic',random_state=1)
  model4 = MLPClassifier(solver='adam', alpha=0.05, hidden_layer_sizes=(100, 50, 30), activation = 'relu', random_state=90)
  model5 = MLPClassifier(solver='lbfgs', alpha=0.0001, hidden_layer_sizes=(120, 80, 40), activation = 'identity', random_state=40)

  '''Train and test'''
  model1.fit(train_features, train_target)
  model2.fit(train_features, train_target)
  model3.fit(train_features, train_target)
  model4.fit(train_features, train_target)
  model5.fit(train_features, train_target)

  preds1 = model1.predict(test_features)
  preds2 = model2.predict(test_features)
  preds3 = model3.predict(test_features)
  preds4 = model4.predict(test_features)
  preds5 = model5.predict(test_features)

  cr1 = confusion_matrix(test_target, preds1)
  cr2 = confusion_matrix(test_target, preds2)
  cr3 = confusion_matrix(test_target, preds3)
  cr4 = confusion_matrix(test_target, preds4)
  cr5 = confusion_matrix(test_target, preds5)

  tn, fp, fn, tp = confusion_matrix(list(test_target), list(preds1), labels=[0, 1]).ravel()
  print('bugs-number:', tn+fn)

  from sklearn.metrics import f1_score

  f1_weighted1 = f1_score(test_target, preds1, average = 'weighted')
  f1_weighted2 = f1_score(test_target, preds2, average = 'weighted')
  f1_weighted3 = f1_score(test_target, preds3, average = 'weighted')
  f1_weighted4 = f1_score(test_target, preds4, average = 'weighted')
  f1_weighted5 = f1_score(test_target, preds5, average = 'weighted')

  f1_macro1 = f1_score(test_target, preds1, average = 'macro')
  f1_macro2 = f1_score(test_target, preds2, average = 'macro')
  f1_macro3 = f1_score(test_target, preds3, average = 'macro')
  f1_macro4 = f1_score(test_target, preds4, average = 'macro')
  f1_macro5 = f1_score(test_target, preds5, average = 'macro')

  f1_micro1 = f1_score(test_target, preds1, average = 'micro')
  f1_micro2 = f1_score(test_target, preds2, average = 'micro')
  f1_micro3 = f1_score(test_target, preds3, average = 'micro')
  f1_micro4 = f1_score(test_target, preds4, average = 'micro')
  f1_micro5 = f1_score(test_target, preds5, average = 'micro')

  f1_score_weighted1 = "%.2f"%round(f1_weighted1, 2)
  f1_score_weighted2 = "%.2f"%round(f1_weighted2, 2)
  f1_score_weighted3 = "%.2f"%round(f1_weighted3, 2)
  f1_score_weighted4 = "%.2f"%round(f1_weighted4, 2)
  f1_score_weighted5 = "%.2f"%round(f1_weighted5, 2)

  f1_score_macro1 = "%.2f"%round(f1_macro1, 2)
  f1_score_macro2 = "%.2f"%round(f1_macro2, 2)
  f1_score_macro3 = "%.2f"%round(f1_macro3, 2)
  f1_score_macro4 = "%.2f"%round(f1_macro4, 2)
  f1_score_macro5 = "%.2f"%round(f1_macro5, 2)

  f1_score_micro1 = "%.2f"%round(f1_micro1, 2)
  f1_score_micro2 = "%.2f"%round(f1_micro2, 2)
  f1_score_micro3 = "%.2f"%round(f1_micro3, 2)
  f1_score_micro4 = "%.2f"%round(f1_micro4, 2)
  f1_score_micro5 = "%.2f"%round(f1_micro5, 2)

  head = PrettyTable(['random_state', 'activation', 'solver', 'hidden_layer_sizestuple', 'alpha', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro']) 
  head.add_row(['', '', '', '', '', cr1, f1_score_weighted1, f1_score_macro1, f1_score_micro1]) 
  head.add_row(['10', 'tanh', 'lbfgs', '(5, 2)', '0.01', cr2, f1_score_weighted2, f1_score_macro2, f1_score_micro2]) 
  head.add_row(['1', 'logistic', 'sgd', '(150, 100, 50)', 'le-5', cr3, f1_score_weighted3, f1_score_macro3, f1_score_micro3]) 
  head.add_row(['90', 'relu', 'adam', '(100, 50, 30)', '0.05', cr4, f1_score_weighted4, f1_score_macro4, f1_score_micro4]) 
  head.add_row(['40', 'identity', 'lbfgs', '(120, 80, 40)', '0.0001', cr5, f1_score_weighted5, f1_score_macro5, f1_score_micro5]) 
  print(head)

Multi layer perceptron neural network
Project: elasticsearch


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_resu

bugs-number: 2474
+--------------+------------+--------+-------------------------+--------+--------------------------------------------------+-------------------+----------------+----------------+
| random_state | activation | solver | hidden_layer_sizestuple | alpha  |                 confusion_matrix                 | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+------------+--------+-------------------------+--------+--------------------------------------------------+-------------------+----------------+----------------+
|              |            |        |                         |        | [[1670 1336   74   48    1    0    3    0    0]  |        0.41       |      0.13      |      0.43      |
|              |            |        |                         |        |  [ 804  960   51   46    2    0    3    0    0]  |                   |                |                |
|              |            |        |                         |        |  [ 310  472  

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


bugs-number: 44
+--------------+------------+--------+-------------------------+--------+------------------+-------------------+----------------+----------------+
| random_state | activation | solver | hidden_layer_sizestuple | alpha  | confusion_matrix | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+------------+--------+-------------------------+--------+------------------+-------------------+----------------+----------------+
|              |            |        |                         |        |  [[30 37  5  1]  |        0.45       |      0.26      |      0.42      |
|              |            |        |                         |        |   [14 14  2  1]  |                   |                |                |
|              |            |        |                         |        |   [ 0  2  1  0]  |                   |                |                |
|              |            |        |                         |        |  [ 0  0  0  0]]  |          

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


bugs-number: 11
+--------------+------------+--------+-------------------------+--------+------------------+-------------------+----------------+----------------+
| random_state | activation | solver | hidden_layer_sizestuple | alpha  | confusion_matrix | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+------------+--------+-------------------------+--------+------------------+-------------------+----------------+----------------+
|              |            |        |                         |        |      [[8 5]      |        0.56       |      0.43      |      0.53      |
|              |            |        |                         |        |      [3 1]]      |                   |                |                |
|      10      |    tanh    | lbfgs  |          (5, 2)         |  0.01  |     [[12  1]     |        0.63       |      0.41      |      0.71      |
|              |            |        |                         |        |     [ 4  0]]     |          

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


bugs-number: 432
+--------------+------------+--------+-------------------------+--------+-----------------------------------------------------+-------------------+----------------+----------------+
| random_state | activation | solver | hidden_layer_sizestuple | alpha  |                   confusion_matrix                  | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+------------+--------+-------------------------+--------+-----------------------------------------------------+-------------------+----------------+----------------+
|              |            |        |                         |        |  [[318  17  35  14   0   0   1   5   0   0   0   1] |        0.47       |      0.12      |      0.51      |
|              |            |        |                         |        |   [114  19  28  11   0   0   0  10   0   0   0   0] |                   |                |                |
|              |            |        |                         |        |

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


Support vector machine

In [1]:
print('Support vector machine')
projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:
  print(f'Project: {project}')

  '''Read data from CSV with Pandas'''
  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")

  '''Split into train and test with numpy (0.75 train, 0.25 test)'''
  from sklearn.model_selection import train_test_split
  train, test = train_test_split(df, test_size=0.25)

  df=(df-df.mean())/df.std()

  test_target = test.pop('Number of Bugs')
  test_features = test
 
  train_target = train.pop('Number of Bugs')
  train_features = train
  
  '''Create Artificial Neural Network classifier'''
  model1 = SVC()
  model2 = SVC(kernel='sigmoid', C=100, gamma=1, random_state=85)
  model3 = SVC(kernel='rbf', C=0.1, gamma=0.01, random_state=15)
  model4 = SVC(kernel='linear', C=1, gamma=0.001, random_state=74)

  '''Train and test'''
  model1.fit(train_features, train_target)
  model2.fit(train_features, train_target)
  model3.fit(train_features, train_target)
  model4.fit(train_features, train_target)

  preds1 = model1.predict(test_features)
  preds2 = model2.predict(test_features)
  preds3 = model3.predict(test_features)
  preds4 = model4.predict(test_features)

  cr1 = confusion_matrix(test_target, preds1)
  cr2 = confusion_matrix(test_target, preds2)
  cr3 = confusion_matrix(test_target, preds3)
  cr4 = confusion_matrix(test_target, preds4)

  tn, fp, fn, tp = confusion_matrix(list(test_target), list(preds1), labels=[0, 1]).ravel()
  print('bugs-number:', tn+fn)

  from sklearn.metrics import f1_score

  f1_weighted1 = f1_score(test_target, preds1, average = 'weighted')
  f1_weighted2 = f1_score(test_target, preds2, average = 'weighted')
  f1_weighted3 = f1_score(test_target, preds3, average = 'weighted')
  f1_weighted4 = f1_score(test_target, preds4, average = 'weighted')

  f1_macro1 = f1_score(test_target, preds1, average = 'macro')
  f1_macro2 = f1_score(test_target, preds2, average = 'macro')
  f1_macro3 = f1_score(test_target, preds3, average = 'macro')
  f1_macro4 = f1_score(test_target, preds4, average = 'macro')

  f1_micro1 = f1_score(test_target, preds1, average = 'micro')
  f1_micro2 = f1_score(test_target, preds2, average = 'micro')
  f1_micro3 = f1_score(test_target, preds3, average = 'micro')
  f1_micro4 = f1_score(test_target, preds4, average = 'micro')

  f1_score_weighted1 = "%.2f"%round(f1_weighted1, 2)
  f1_score_weighted2 = "%.2f"%round(f1_weighted2, 2)
  f1_score_weighted3 = "%.2f"%round(f1_weighted3, 2)
  f1_score_weighted4 = "%.2f"%round(f1_weighted4, 2)

  f1_score_macro1 = "%.2f"%round(f1_macro1, 2)
  f1_score_macro2 = "%.2f"%round(f1_macro2, 2)
  f1_score_macro3 = "%.2f"%round(f1_macro3, 2)
  f1_score_macro4 = "%.2f"%round(f1_macro4, 2)

  f1_score_micro1 = "%.2f"%round(f1_micro1, 2)
  f1_score_micro2 = "%.2f"%round(f1_micro2, 2)
  f1_score_micro3 = "%.2f"%round(f1_micro3, 2)
  f1_score_micro4 = "%.2f"%round(f1_micro4, 2)

  head = PrettyTable(['random_state', 'c', 'gamma', 'kernel', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro']) 
  head.add_row(['', '', '', '', cr1, f1_score_weighted1, f1_score_macro1, f1_score_micro1]) 
  head.add_row(['85', '100', '1', 'sigmoid', cr2, f1_score_weighted2, f1_score_macro2, f1_score_micro2]) 
  head.add_row(['15', '0.01', '0.01', 'rbf', cr4, f1_score_weighted4, f1_score_macro4, f1_score_micro4]) 
  head.add_row(['74', '1', '0.001', 'linear', cr5, f1_score_weighted5, f1_score_macro5, f1_score_micro5]) 
  print(head)

Support vector machine
Project: elasticsearch


NameError: ignored

decision tree

In [17]:
print('Decision tree')
projects = ['elasticsearch', 'titan', 'mct', 'BroadleafCommerce']

for project in projects:
  print(f'Project: {project}')

  '''Read data from CSV with Pandas'''
  _file =f"drive/MyDrive/subtract/{project}/class.csv"
  cols = list(pd.read_csv(_file, nrows =1).dropna(axis='columns', how='all'))

  df = pd.read_csv(_file, usecols =cols)
  df.pop('LongName')
  df.pop('Hash')
  df = df.T.drop_duplicates().T
  df.describe(include="all")

  '''Split into train and test with numpy (0.75 train, 0.25 test)'''
  from sklearn.model_selection import train_test_split
  train, test = train_test_split(df, test_size=0.25)

  df=(df-df.mean())/df.std()

  test_target = test.pop('Number of Bugs')
  test_features = test
 
  train_target = train.pop('Number of Bugs')
  train_features = train

  head = PrettyTable(['random_state', 'max_depth', 'confusion_matrix', 'f1_score_weighted', 'f1_score_macro', 'f1_score_micro']) 
  
  max_depth_range = list(range(1, 15))
  for depth in max_depth_range:

    '''Create decision tree classifier'''    
    model = tree.DecisionTreeClassifier(max_depth = depth,  random_state = 90)
  
    '''Train and test'''
    model.fit(train_features, train_target)
    preds = model.predict(test_features)

    cr = confusion_matrix(test_target, preds)

    from sklearn.metrics import f1_score

    f1_weighted = f1_score(test_target, preds, average = 'weighted')
    f1_macro = f1_score(test_target, preds, average = 'macro')
    f1_micro = f1_score(test_target, preds, average = 'micro')

    f1_score_weighted = "%.2f"%round(f1_weighted, 2)
    f1_score_macro = "%.2f"%round(f1_macro, 2)
    f1_score_micro = "%.2f"%round(f1_micro, 2)

    head.add_row(['90', depth, cr, f1_score_weighted, f1_score_macro, f1_score_micro]) 

  tn, fp, fn, tp = confusion_matrix(list(test_target), list(preds), labels=[0, 1]).ravel()
  print('bugs-number:', tn+fn)

  print(head)
  


Decision tree
Project: elasticsearch
bugs-number: 3327
+--------------+-----------+--------------------------------------------------+-------------------+----------------+----------------+
| random_state | max_depth |                 confusion_matrix                 | f1_score_weighted | f1_score_macro | f1_score_micro |
+--------------+-----------+--------------------------------------------------+-------------------+----------------+----------------+
|      90      |     1     | [[3124    0    0    0    0    0    0    0    0]  |        0.33       |      0.07      |      0.50      |
|              |           |  [1922    0    0    0    0    0    0    0    0]  |                   |                |                |
|              |           |  [ 809    0    0    0    0    0    0    0    0]  |                   |                |                |
|              |           |  [ 281    0    0    0    0    0    0    0    0]  |                   |                |                |
|      